function export_runtime_summary_chart()

repoRoot = fileparts(fileparts(mfilename('fullpath')));
figuresDir = fullfile(repoRoot, 'figures');
if ~isfolder(figuresDir)
  mkdir(figuresDir);
end

caseNames = {
  'Classical OC sens.'
  'MTOP OC sens.'
  'MTOP MMA sens.'
  'Classical OC dens.'
  'MTOP OC dens.'
  'MTOP MMA dens.'
  'MTOP MMA Heav. \eta=0.3'
  'MTOP MMA Heav. \eta=0.5'
  'MTOP MMA Heav. \eta=0.7'
};

iterations = [94; 95; 250; 237; 299; 419; 419; 563; 522];
timeSeconds = [263.23; 12.28; 187.28; 692.91; 136.57; 253.89; ...
  278.63; 370.87; 327.98];
nativeCompliance = [224.596; 219.069; 220.875; 241.083; 235.363; ...
  234.456; 194.446; 193.756; 195.061];
fineCompliance = [224.596; 224.696; 226.502; 241.083; 240.984; ...
  240.077; 200.016; 199.326; 200.633];
stopByCompliance = [false; false; false; true; true; true; false; false; false];

nCases = numel(caseNames);
y = 1:nCases;

timeColors = zeros(nCases, 3);
timeColors(1:3, :) = repmat([0.24 0.45 0.70], 3, 1);
timeColors(4:6, :) = repmat([0.12 0.62 0.56], 3, 1);
timeColors(7:9, :) = repmat([0.50 0.35 0.72], 3, 1);

fig = figure('Visible', 'off', 'Color', 'w', 'Units', 'centimeters', ...
  'Position', [2 2 18.4 13.6]);
layout = tiledlayout(fig, 1, 2, 'TileSpacing', 'compact', ...
  'Padding', 'compact');

axTime = nexttile(layout, 1);
hold(axTime, 'on');
grid(axTime, 'on');
box(axTime, 'off');
for idx = 1:nCases
  barh(axTime, y(idx), timeSeconds(idx), 0.62, ...
    'FaceColor', timeColors(idx, :), 'EdgeColor', 'none', ...
    'HandleVisibility', 'off');
end
set(axTime, 'YDir', 'reverse', 'YTick', y, 'YTickLabel', caseNames, ...
  'FontName', 'Arial', 'FontSize', 8.4, 'LineWidth', 0.8, ...
  'GridAlpha', 0.16, 'TickDir', 'out');
xlabel(axTime, 'Wall-clock time [s]');
title(axTime, 'Cost and stopping behavior', 'FontWeight', 'bold');
xlim(axTime, [0 750]);
xticks(axTime, 0:150:750);
ylim(axTime, [0.35 nCases + 0.65]);
plot(axTime, [0 750], [3.5 3.5], '-', 'Color', [0.82 0.82 0.82], ...
  'LineWidth', 0.8, 'HandleVisibility', 'off');
plot(axTime, [0 750], [6.5 6.5], '-', 'Color', [0.82 0.82 0.82], ...
  'LineWidth', 0.8, 'HandleVisibility', 'off');

for idx = 1:nCases
  text(axTime, timeSeconds(idx) + 10, y(idx), ...
    sprintf('%.0f s  |  %d it.', timeSeconds(idx), iterations(idx)), ...
    'FontName', 'Arial', 'FontSize', 7.6, 'Color', [0.12 0.12 0.12], ...
    'VerticalAlignment', 'middle');
  if stopByCompliance(idx)
    marker = 's';
    markerColor = [0.88 0.52 0.13];
  else
    marker = 'o';
    markerColor = [0.18 0.55 0.22];
  end
  plot(axTime, 8, y(idx), marker, 'MarkerSize', 5.7, ...
    'MarkerFaceColor', markerColor, 'MarkerEdgeColor', 'w', ...
    'LineWidth', 0.7, 'HandleVisibility', 'off');
end

hChange = plot(axTime, nan, nan, 'o', 'MarkerSize', 5.7, ...
  'MarkerFaceColor', [0.18 0.55 0.22], 'MarkerEdgeColor', 'w', ...
  'DisplayName', 'change stop');
hCompliance = plot(axTime, nan, nan, 's', 'MarkerSize', 5.7, ...
  'MarkerFaceColor', [0.88 0.52 0.13], 'MarkerEdgeColor', 'w', ...
  'DisplayName', 'compliance stop');
legend(axTime, [hChange hCompliance], 'Location', 'southoutside', ...
  'Orientation', 'horizontal', ...
  'Box', 'off', 'FontSize', 7.8);

axCompliance = nexttile(layout, 2);
hold(axCompliance, 'on');
grid(axCompliance, 'on');
box(axCompliance, 'off');
set(axCompliance, 'YDir', 'reverse', 'YTick', y, 'YTickLabel', [], ...
  'FontName', 'Arial', 'FontSize', 8.4, 'LineWidth', 0.8, ...
  'GridAlpha', 0.16, 'TickDir', 'out');
xlabel(axCompliance, 'Compliance C');
title(axCompliance, 'Fine-mesh compliance is the comparison value', ...
  'FontWeight', 'bold');
xlim(axCompliance, [188 247]);
xticks(axCompliance, 190:10:245);
ylim(axCompliance, [0.35 nCases + 0.65]);
plot(axCompliance, [188 247], [3.5 3.5], '-', 'Color', [0.82 0.82 0.82], ...
  'LineWidth', 0.8, 'HandleVisibility', 'off');
plot(axCompliance, [188 247], [6.5 6.5], '-', 'Color', [0.82 0.82 0.82], ...
  'LineWidth', 0.8, 'HandleVisibility', 'off');

for idx = 1:nCases
  plot(axCompliance, [nativeCompliance(idx) fineCompliance(idx)], ...
    [y(idx) y(idx)], '-', 'Color', [0.70 0.70 0.70], ...
    'LineWidth', 1.3, 'HandleVisibility', 'off');
  plot(axCompliance, nativeCompliance(idx), y(idx), 'o', ...
    'MarkerSize', 5.3, 'MarkerFaceColor', [0.12 0.35 0.66], ...
    'MarkerEdgeColor', 'w', 'LineWidth', 0.7, ...
    'HandleVisibility', 'off');
  plot(axCompliance, fineCompliance(idx), y(idx), 'd', ...
    'MarkerSize', 6.6, 'MarkerFaceColor', [0.86 0.38 0.16], ...
    'MarkerEdgeColor', 'w', 'LineWidth', 0.7, ...
    'HandleVisibility', 'off');
  text(axCompliance, fineCompliance(idx) + 0.8, y(idx), ...
    sprintf('%.1f', fineCompliance(idx)), 'FontName', 'Arial', ...
    'FontSize', 7.5, 'Color', [0.12 0.12 0.12], ...
    'VerticalAlignment', 'middle');
end

hNative = plot(axCompliance, nan, nan, 'o', 'MarkerSize', 5.3, ...
  'MarkerFaceColor', [0.12 0.35 0.66], 'MarkerEdgeColor', 'w', ...
  'DisplayName', 'native C');
hFine = plot(axCompliance, nan, nan, 'd', 'MarkerSize', 5.8, ...
  'MarkerFaceColor', [0.86 0.38 0.16], 'MarkerEdgeColor', 'w', ...
  'DisplayName', 'fine C (compare)');
legend(axCompliance, [hNative hFine], 'Location', 'southoutside', ...
  'Orientation', 'horizontal', ...
  'Box', 'off', 'FontSize', 7.8);

text(axCompliance, 190.5, 8.43, 'Heaviside projection gives the lowest C', ...
  'FontName', 'Arial', 'FontSize', 8.1, 'FontWeight', 'bold', ...
  'Color', [0.34 0.22 0.50], 'BackgroundColor', 'w', 'Margin', 2.2);
plot(axCompliance, [199.326 199.326], [7.65 8.25], '-', ...
  'Color', [0.34 0.22 0.50], 'LineWidth', 1.1, 'HandleVisibility', 'off');

exportgraphics(fig, fullfile(figuresDir, 'runtime_summary_chart.png'), ...
  'Resolution', 300);
exportgraphics(fig, fullfile(figuresDir, 'runtime_summary_chart.pdf'), ...
  'ContentType', 'vector');
close(fig);
end
